name: geotag
description: Tags on a map, like a journal of locations + some social element

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.4.5
  firebase_analytics: ^5.0.16
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7

  hive: ^1.4.2
  hive_flutter: ^0.3.1
  path_provider: ^1.6.11

  cached_network_image: ^2.2.0+1

  google_maps_flutter: ^0.5.28+1
  geolocator: ^5.3.2+2

  feather_icons_flutter: ^4.7.4
  font_awesome_flutter: ^8.8.1
  flutter_sfsymbols: ^1.0.0
  cupertino_icons: ^0.1.3
  google_fonts: ^1.1.0
  flutter_neumorphic: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.1
  build_runner: ^1.10.0
  flutter_launcher_icons: ^0.7.5

dependency_overrides:
  dartx: ^0.5.0
  quiver: ^2.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  ios: true
  android: true
  image_path: "assets/geotag_icon/1024.png"

fonts:
  - family: sficonsets
    fonts:
      - assets: packages/flutter_sfsymbols/fonts/sficonsets.ttf