name: geotag
description: Tags on a map, like a journal of locations + some social element

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.4.4+3
  firebase_analytics: ^5.0.11
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5

  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  path_provider: ^1.6.8

  google_maps_flutter: ^0.5.27+3
  geolocator: ^5.3.1

  feather_icons_flutter: ^4.7.4
  cupertino_icons: ^0.1.3
  google_fonts: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.0+2
  build_runner: ^1.10.0
  flutter_launcher_icons: ^0.7.5

dependency_overrides:
  dartx: ^0.4.1
  quiver: ^2.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  image_path_android: "assets/geotag_icon/playstore.png"
  image_path_ios: "assets/geotag_icon/appstore.png"
  android: true
  ios: true
